server:
  port: 8761

eureka:
  instance:
    hostname: ${HOSTNAME.eureka:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:localhost}
